### ISSUE TITLE
Can exoplayer be migrated to media3

### ISSUE THREAD

**Issue by marufbd** [jslowinski/MusicPlayer#4]
I was struggling to migrate the exoplayer2 codes to the latest media3 now that media3 is out from beta to v1.0.0.
I was following this guide, but getting lost after some time.
[Migration guide](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide#MediaSessionConnector)

Do you have any plans to migrate the exoplayer codes to media3, i think that would make this as a complete reference music player.

**Comment by jslowinski** [comment]
The application has a couple of bugs that need to be resolved but has been rewritten for the media3 library
